### PR TITLE
Fix how threads are parsed

### LINKED ISSUE #116: Threads are broken more often recently
It seems to me that threads do not show correctly more often than before lately.

I'd love to hear what other people think about this, it's been a few months since I haven't followed the latest discussions so I may be wrong.

Looking at threads in the home page many responses are not linked to the parent email, and it doesn't seem to affect only specific users…

### PR DESCRIPTION
**Pull request by mnapoli**
Trying to fix threads.

Closes #116

### CODE REVIEW

File: src/EmailSynchronizer.php [hunk 1]
```diff
@@ -226,4 +248,20 @@ private function parseDateTime(Message $parsedDocument)
 
         return $date;
     }
+
+    private function findEmailThreadId(string $inReplyTo): ?string
+    {
+        try {
+            $email = $this->emailRepository->getById($inReplyTo);
+        } catch (NotFound $e) {
+            // We did find the thread, let's move on
```
Comment (gharlan) [inline src/EmailSynchronizer.php]: "didn't"?

File: src/EmailSynchronizer.php [hunk 2]
```diff
@@ -226,4 +248,20 @@ private function parseDateTime(Message $parsedDocument)
...
+            return null;
+        }
+        // If the email is not a thread root then we return the thread root ID
+        if ($email->getThreadId()) {
```
Comment (gharlan) [inline src/EmailSynchronizer.php]: Can the thread id be `null`? In line 193 it is set to the email id for root mails.

File: src/EmailSynchronizer.php (hunk 1 above)
Comment (mnapoli) [reply src/EmailSynchronizer.php]: :+1: thanks

File: src/EmailSynchronizer.php (hunk 2 above)
Comment (mnapoli) [reply src/EmailSynchronizer.php]: Thanks, I have added more comments to explain.

Here the threadId can be null because we could be replying to the thread root (the thread root has a `null` getThreadId()).

Comment (gharlan) [reply src/EmailSynchronizer.php]: > (the thread root has a `null` getThreadId()).

Hmm, I don't think so, because of line 191-194:
https://github.com/mnapoli/externals/pull/120/files#diff-8133c15998ef143392dabbf7350cbf36R191-R194

So I think before this pull request the thread id for root mails was `null`, but with this pr they are equal to the email id (for root mails).

Comment (mnapoli) [reply src/EmailSynchronizer.php]: Oh that is a good point you are correct. I checked in the database as well and it's not null.

So it should always return here. I don't feel comfortable changing the code (making the getter return a non-nullable `string` and making the database column not nullable) because the PR already changes many things, I'd rather limit the scope of the change ^^

But thanks! It's something I should improve later.

**Comment by mnapoli** [comment]
Let's give this a try!

If it works maybe I'll try to reprocess all past messages.

File: src/Email/EmailRepository.php [hunk 3]
```diff
@@ -211,7 +211,7 @@ public function add(Email $email)
             'datetime',
             'string',
             'string',
-            'integer',
+            'string',
```
Comment (mnapoli) [inline src/Email/EmailRepository.php]: This was a nasty bug: all thread IDs were turned into 0.

I think because we had so many problems deploying with platform.sh we may have been running a very old version of the code for a long time (before we migrated away from it).

**Comment by mnapoli** [comment]
It seems to have done the trick! Now I want to try to figure out if I can reasonably re-parse all mails in the history 🤔 

Anyway at least it works now!

File: src/Email/EmailRepository.php (hunk 3 above)
Comment (staabm) [reply src/Email/EmailRepository.php]: Maybe this is something you can check with e.g. https://github.com/webmozart/assert and let psalm detect these errors with a CI build
